-keep class com.pay.sky.data.** { *; }
-keep class com.pay.sky.receiver.** { *; }
-keep class com.pay.sky.service.** { *; }
-keep class com.pay.sky.ui.** { *; }
-keep class com.pay.sky.util.** { *; }
